CC = gcc
DEBUG = -Wall -g

.PHONY: clean

OBJECTS = main.o win.o controls.o choice.o

all: setup

setup: $(OBJECTS)
	$(CC) $(DEBUG) $(OBJECTS) -o $@ -lalleg

main.o: main.c main.h
	$(CC) $(DEBUG) -c $< -o $@
	
controls.o: controls.c controls.h
	$(CC) $(DEBUG) -c $< -o $@
	
choice.o: choice.c choice.h
	$(CC) $(DEBUG) -c $< -o $@
	
win.o: win.c win.h
	$(CC) $(DEBUG) -c $< -o $@

clean:
	del /S *.o
	del setup.exe
